### ISSUE TITLE
republish to npm?

### ISSUE THREAD

**Issue by bengl** [azer/strip#6]
Some of our projects use this package, and it would be most awesome if this package were republished to npm to reduce further shenanigans.

I'm not sure what the current state of affairs is, but if there's a need or desire for someone else to take on ownership or publishing, I'm happy to do so.

**Comment by halbgut** [comment]
From the looks of it azer has a lot on his hands right now and this isn't exactly his most popular package. So I went ahead, forked it and request the name at the Npm support.

Hope I'm not being to forward here. :)

**Comment by bengl** [comment]
@Kriegslustig great :+1: looking forward to a re-release.

**Comment by DylanPiercey** [comment]
@bengl I ended up switching to https://github.com/ericnorris/striptags which works as a drop in replacement but has more features (and is still light weight).

**Comment by azer** [comment]
[I will no longer publish to NPM](https://medium.com/@azerbike/i-ve-just-liberated-my-modules-9045c06be67c) let me know if you want to take oenwership of this package

**Comment by DylanPiercey** [comment]
@azer I'll take ownership if you don't mind. Do I just clone this and republish at a new major version?

**Comment by azer** [comment]
@DylanPiercey done, you're also owner in this repo. so you can manage it. you need to deal with npm ownership with them

**Comment by DylanPiercey** [comment]
Awesome - thanks @azer.
Hope the dust settles soon.
